export const AUTH_USER = 'AUTH_USER';

export const FETCH_USER_PROPERTIES = 'FETCH_USER_PROPERTIES';
export const FETCH_PROJECT = 'FETCH_PROJECT';
export const FETCH_USER_PROPERTY = 'FETCH_USER_PROPERTY';
export const DELETE_SELECTED_PROPERTY = 'DELETE_SELECTED_PROPERTY';

// PROJECTs
export const FETCH_PROJECTS = 'FETCH_PROJECTS';
export const DELETE_PROJECT = 'DELETE_PROJECT';

// Project Posts
export const RECEIVE_PROJECT_POSTS = 'RECEIVE_PROJECT_POSTS';
export const REQUEST_PROJECT_POSTS = 'REQUEST_PROJECT_POSTS';
export const HANDLE_EMPTY_PROJECT_POSTS = 'HANDLE_EMPTY_PROJECT_POSTS';
export const SELECT_PROJECT_POST = 'SELECT_PROJECT_POST';

// MAP DATA
export const RECEIVE_MAP_DATA = 'RECEIVE_MAP_DATA';
export const REQUEST_MAP_DATA = 'REQUEST_MAP_DATA';
