export const FETCH_CURRENT_USER_DATA = 'FETCH_CURRENT_USER_DATA';
export const FETCH_PROPERTY_DATA = 'FETCH_PROPERTY_DATA';
export const FETCH_MAP_DATA = 'FETCH_MAP_DATA';
export const LOADING_DATA = 'LOADING_DATA';
export const RESET_PROP_DATA = 'RESET_PROP_DATA';
